name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup git config
        run: |
          git config user.name "Prathamesh Patil"
          git config user.email "prathameshpatil2812@gmail.com"

      - name: setup react deployment
        run: |
          npm install
          rm -rf dist
          npm run build
          git add dist -f
          git commit -m "react build files - github action"
          git push

